package main

// invertStringIntMap receives a map[string][int], swaps the keys for values and returns a map[int][string]
func invertStringIntMap(mapToInvert map[string]int) map[int]string {
	var newMap map[int]string
	for k, v := range mapToInvert {
		newMap[v] = k
	}
	return newMap
}

// punctuationToTokens returns a map of punctuation symbols to token ids
func punctuationToTokens() map[string]int {
	return map[string]int{
		":": PnStatementSeparator,
		",": PnValueSeparator,
		";": PnCoordinateSeperator,
		"(": PnLeftParenthesis,
		")": PnRightParenthesis,
	}
}

// tokensToPunctuation returns a map of tokens to punctuation symbols
func tokensToPunctuation() map[int]string {
	return invertStringIntMap(punctuationToTokens())
}

// mathematicalToTokens returns a map of mathematical symbols to token ids
func mathematicalToTokens() map[string]int {
	return map[string]int{
		":=": MaAssign,
		"^":  MaExponential,
		"+":  MaAddition,
		"-":  MaSubtraction,
		"*":  MaMultiplication,
		"/":  MaDivision,
		"\\": MaIntegerDivision,
		"=":  MaEquality,
		"<>": MaInequality1,
		"><": MaInequality2,
		"<":  MaLessThan,
		">":  MaGreaterThan,
		"<=": MaLessThanEqualTo1,
		"=<": MaLessThanEqualTo2,
		">=": MaGreaterThanEqualTo1,
		"=>": MaGreaterThanEqualTo2,
		"==": MaInterestinglyEqual,
	}
}

// tokensToMathematical returns a map of tokens to mathematical symbols
func tokensToMathematical() map[int]string {
	return invertStringIntMap(mathematicalToTokens())
}

// keywordsToTokens returns a map of keyword symbols to token ids
func keywordsToTokens() map[string]int {
	return map[string]int{
		"ABS":        KwABS,
		"AND":        KwAND,
		"AREA":       KwAREA,
		"ASC":        KwASC,
		"ASK":        KwASK,
		"ATN":        KwATN,
		"AUTO":       KwAUTO,
		"BLOCK":      KwBLOCK,
		"COPY":       KwCOPY,
		"READ":       KwREAD,
		"WRITE":      KwWRITE,
		"BORDER":     KwBORDER,
		"BOUNDS":     KwBOUNDS,
		"BRUSH":      KwBRUSH,
		"BUTTONS":    KwBUTTONS,
		"BYE":        KwBYE,
		"CHAROVER":   KwCHAROVER,
		"CHARSET":    KwCHARSET,
		"CHDIR":      KwCHDIR,
		"CHR$":       KwCHRstr,
		"CIRCLE":     KwCIRCLE,
		"CLEAR":      KwCLEAR,
		"CLG":        KwCLG,
		"CLL":        KwCLL,
		"CLOSE":      KwCLOSE,
		"CLS":        KwCLS,
		"COLOUR":     KwCOLOUR,
		"CONTINUE":   KwCONTINUE,
		"COS":        KwCOS,
		"CREATE":     KwCREATE,
		"MOVE":       KwMOVE,
		"CURPOS":     KwCURPOS,
		"CURSOR":     KwCURSOR,
		"DATA":       KwDATA,
		"DATE":       KwDATE,
		"DATE$":      KwDATEstr,
		"DEFINED":    KwDEFINED,
		"DEG":        KwDEG,
		"DELETE":     KwDELETE,
		"DIM":        KwDIM,
		"DIR":        KwDIR,
		"DRAWING":    KwDRAWING,
		"EDIT":       KwEDIT,
		"END":        KwEND,
		"ENVELOPE":   KwENVELOPE,
		"ERASE":      KwERASE,
		"ERL":        KwERL,
		"ERR":        KwERR,
		"ERR$":       KwERRstr,
		"EXP":        KwEXP,
		"FALSE":      KwFALSE,
		"FKEY":       KwFKEY,
		"FLOOD":      KwFLOOD,
		"EDGE":       KwEDGE,
		"FLUSH":      KwFLUSH,
		"FOR":        KwFOR,
		"NEXT":       KwNEXT,
		"FREE":       KwFREE,
		"FSPACE":     KwFSPACE,
		"FUNCTION":   KwFUNCTION,
		"ENDFUN":     KwENDFUN,
		"GET":        KwGET,
		"GET$":       KwGETstr,
		"GLOBAL":     KwGLOBAL,
		"GOSUB":      KwGOSUB,
		"SUBROUTINE": KwSUBROUTINE,
		"GOTO":       KwGOTO,
		"HEX$":       KwHEXstr,
		"HOLD":       KwHOLD,
		"HOME":       KwHOME,
		"IF":         KwIF,
		"THEN":       KwTHEN,
		"ELSE":       KwELSE,
		"INPUT":      KwINPUT,
		"INSTR":      KwINSTR,
		"INT":        KwINT,
		"JOYSTICK":   KwJOYSTICK,
		"JOYX":       KwJOYX,
		"JOYY":       KwJOYY,
		"KEYREP":     KwKEYREP,
		"LEAVE":      KwLEAVE,
		"LEFT$":      KwLEFTstr,
		"LEN":        KwLEN,
		"LET":        KwLET,
		"LINE":       KwLINE,
		"LIST":       KwLIST,
		"LN":         KwLN,
		"LOAD":       KwLOAD,
		"LOADGO":     KwLOADGO,
		"LOG":        KwLOG,
		"LOOKUP":     KwLOOKUP,
		"LVAR":       KwLVAR,
		"MEM":        KwMEM,
		"MERGE":      KwMERGE,
		"MERGEGO":    KwMERGEGO,
		"MID$":       KwMIDstr,
		"MIX":        KwMIX,
		"MKDIR":      KwMKDIR,
		"MOD":        KwMOD,
		"MODE":       KwMODE,
		"MOUSE":      KwMOUSE,
		"NEW":        KwNEW,
		"NOISE":      KwNOISE,
		"NOT":        KwNOT,
		"NOTE":       KwNOTE,
		"ON":         KwON,
		"BREAK":      KwBREAK,
		"EOF":        KwEOF,
		"ERROR":      KwERROR,
		"OPEN":       KwOPEN,
		"OR":         KwOR,
		"ORIGIN":     KwORIGIN,
		"OVER":       KwOVER,
		"PAPER":      KwPAPER,
		"PATH$":      KwPATHstr,
		"PATTERN":    KwPATTERN,
		"PEN":        KwPEN,
		"PI":         KwPI,
		"PITCH":      KwPITCH,
		"PLOT":       KwPLOT,
		"DIRECTION":  KwDIRECTION,
		"FONT":       KwFONT,
		"CHAR":       KwCHAR,
		"SIZE":       KwSIZE,
		"POINTS":     KwPOINTS,
		"POS":        KwPOS,
		"POSX":       KwPOSX,
		"POSY":       KwPOSY,
		"PRINT":      KwPRINT,
		"PROCEDURE":  KwPROCEDURE,
		"ENDPROC":    KwENDPROC,
		"PROCS":      KwPROCS,
		"PSAVE":      KwPSAVE,
		"PUT":        KwPUT,
		"QUEUE":      KwQUEUE,
		"RAD":        KwRAD,
		"REM":        KwREM,
		"RENAME":     KwRENAME,
		"TO":         KwTO,
		"RENUMBER":   KwRENUMBER,
		"REPEAT":     KwREPEAT,
		"UNTIL":      KwUNTIL,
		"RESTORE":    KwRESTORE,
		"RESULT":     KwRESULT,
		"RESUME":     KwRESUME,
		"RETURN":     KwRETURN,
		"RIGHT$":     KwRIGHTstr,
		"RMDIR":      KwRMDIR,
		"RND":        KwRND,
		"RPOINT":     KwRPOINT,
		"RUN":        KwRUN,
		"SAVE":       KwSAVE,
		"SGN":        KwSGN,
		"SIN":        KwSIN,
		"SLICE":      KwSLICE,
		"SOUND":      KwSOUND,
		"SPC":        KwSPC,
		"SQR":        KwSQR,
		"STOP":       KwSTOP,
		"STRING$":    KwSTRINGstr,
		"STR$":       KwSTRstr,
		"STYLE":      KwSTYLE,
		"TAB":        KwTAB,
		"TAN":        KwTAN,
		"TIME":       KwTIME,
		"TIME$":      KwTIMEstr,
		"TONE":       KwTONE,
		"TRACE":      KwTRACE,
		"TRUE":       KwTRUE,
		"UNDERLINE":  KwUNDERLINE,
		"VAL":        KwVAL,
		"VERSION":    KwVERSION,
		"VOICE":      KwVOICE,
		"WARN":       KwWARN,
		"WIDTH":      KwWIDTH,
		"WRITING":    KwWRITING,
		"XOR":        KwXOR,
		"SET":        KwSET,
	}
}

// tokensToKeywords returns a map of tokens to keywords
func tokensToKeywords() map[int]string {
	return invertStringIntMap(keywordsToTokens())
}
